# ---------------------------------------------------
# File Name: NeonFiles.py
# Author: NeonAnurag
# GitHub: https://github.com/MyselfNeon/
# Telegram: https://t.me/MyelfNeon
# YouTube: https://youtube.com/@MyselfNeon
# Created: 2025-10-21
# Last Modified: 2025-10-22
# Version: Latest
# License: MIT License
# ---------------------------------------------------

class script(object):
    # Plain text with names and URLs
    NEON_TXT = [
    "📌 Absolute Duo - https://t.me/NeonFilesBot?start=Z2V0LTI0NzUxNDI0ODk5MDAwMjktMjQ3MzEzNzUxNDIwOTU0Nw",
    "📌 A Returner's Magic be Special - https://t.me/NeonFilesBot?start=Z2V0LTg0MjA4OTc5MDAwMjQ0LTk3MjQxMzIwOTg4Mzc3",
    "📌 Akashic Records of Magical - https://t.me/NeonFilesBot?start=Z2V0LTEwMDI0ODc4NDUyNDEwMC0xMTMyODExMjY1MTIyMzM",
    "📌 Alya Sometimes hides her - https://t.me/NeonFilesBot?start=Z2V0LTExNDI4MzYxNDM1NzQ3NC0xMjczMTU5NTYzNDU2MDc",
    "📌 An Archdemons Dilemma - https://t.me/NeonFilesBot?start=Z2V0LTExMDQ3NDE2MDU0NTU1ODItMTExNzc3Mzk0NzQ0MzcxNQ",
    "📌 Aristocrats Otherworldly Advent - https://t.me/NeonFilesBot?start=Z2V0LTc4NDk0Nzk4MjgyMzcwMy03OTc5ODAzMjQ4MTE4MzY",
    "📌 Armed Girl's Machiavellism - https://t.me/NeonFilesBot?start=Z2V0LTE5ODY5MzA5MDkyNjc2NjItMjAwMDk2NTczOTEwMTAzNg",
    "📌 Aesthetica of a Rogue Hero - https://t.me/NeonFilesBot?start=Z2V0LTIxOTM0NDM0MDUzODczMDgtMjIwNjQ3NTc0NzM3NTQ0MQ",
    "📌 Attack On Titan - https://t.me/NeonFilesBot?start=Z2V0LTI4NDAwNDgwNjU1Njc3NTMtMjg2NzExNTIzNzM4OTI2MA",
    "📌 Attack On Titan Season 02 - https://t.me/NeonFilesBot?start=Z2V0LTI4NjgxMTc3MjUyMzQ1MDEtMjg4MjE1MjU1NTA2Nzg3NQ",
    "📌 Attack On Titan Season 03 - https://t.me/NeonFilesBot?start=Z2V0LTI4ODMxNTUwNDI5MTMxMTYtMjkwNzIxNDc1MTE5ODkwMA",
    "📌 Attack On Titan Season 04 - https://t.me/NeonFilesBot?start=Z2V0LTI5MDgyMTcyMzkwNDQxNDEtMjkzNzI4OTM4NjU1NjEzMA",
    "📌 Battle Game In 5 Seconds - https://t.me/NeonFilesBot?start=Z2V0LTIxMTgyNTY4MTY5OTQyMzMtMjEzMzI5NDEzNDY3Mjg0OA",
    "📌 Beast Tamer - https://t.me/NeonFilesBot?start=Z2V0LTc5ODk4MjgxMjY1NzA3Ny04MTMwMTc2NDI0OTA0NTE",
    "📌 Berserk of Gluttony - https://t.me/NeonFilesBot?start=Z2V0LTI4NzcxNDAxMTU4NDE2Ny0zMDA3NDYzNTM1NzIzMDA",
    "📌 Black Summoner - https://t.me/NeonFilesBot?start=Z2V0LTExNTQ4NjU5OTc3MTc2MzItMTE2Nzg5ODMzOTcwNTc2NQ",
    "📌 Blue Lock - https://t.me/NeonFilesBot?start=Z2V0LTIyMDg0ODA3MjMwNjU5MjMtMjIzMzU0MjkxOTE5Njk0OA",
    "📌 Blue Lock S2 - https://t.me/NeonFilesBot?start=Z2V0LTIyOTU2OTcxNjU2MDE4OTAtMjMxMDczNDQ4MzI4MDUwNQ",
    "📌 BOFURI: I Don't get Hurt S01 - https://t.me/NeonFilesBot?start=Z2V0LTE2MzAwNDUyMzYzNjE4NjYtMTY0MzA3NzU3ODM0OTk5OQ",
    "📌 BOFURI: I Don't get Hurt S02 - https://t.me/NeonFilesBot?start=Z2V0LTE2NDQwODAwNjYxOTUyNDAtMTY1NzExMjQwODE4MzM3Mw",
    "📌 Buddy Complex - https://t.me/NeonFilesBot?start=Z2V0LTM1MjI3NDIyODgxNzY4NzQtMzUzODc4MjA5MzcwMDczMA",
    "📌 Buddy Complex Specials - https://t.me/NeonFilesBot?start=Z2V0LTM1Mzk3ODQ1ODE1NDU5NzEtMzU0Mjc5MjA0NTA4MTY5NA",
    "📌 Buddy Daddies - https://t.me/NeonFilesBot?start=Z2V0LTE0NjU2MzcyMjk3NDIzNDItMTQ3ODY2OTU3MTczMDQ3NQ",
    "📌 Campfire Cooking in Another - https://t.me/NeonFilesBot?start=Z2V0LTMyOTgxODUwMTA4NDI4OS0zNDI4NTA4NDMwNzI0MjI",
    "📌 Cautious Hero - https://t.me/NeonFilesBot?start=Z2V0LTM0NDk1NjA2NzU0NzQyODEtMzQ2MzU5NTUwNTMwNzY1NQ",
    "📌 ChainSaw Man - https://t.me/NeonFilesBot?start=Z2V0LTQzMjA3MjI2MTI5ODg3MS00NDUxMDQ2MDMyODcwMDQ",
    "📌 Chained Soldier - https://t.me/NeonFilesBot?start=Z2V0LTMxNTU4MzE3MzY4MTg2NjgtMzE2OTg2NjU2NjY1MjA0Mg",
    "📌 Chaika Avenging Battle - https://t.me/NeonFilesBot?start=Z2V0LTI0NDAwNTU0MTUzMTY1OTQtMjQ1MjA4NTI2OTQ1OTQ4Ng",
    "📌 Chaika Coffin Princess - https://t.me/NeonFilesBot?start=Z2V0LTI0MjQwMTU2MDk3OTI3MzgtMjQzNzA0Nzk1MTc4MDg3MQ",
    "📌 Chivalry Of a Failed Knight - https://t.me/NeonFilesBot?start=Z2V0LTgzMDA1OTkzNTg1OTU0OC04NDMwOTIyNzc4NDc2ODE",
    "📌 Code:Breaker - https://t.me/NeonFilesBot?start=Z2V0LTMyMTY5ODM0OTUzNzgzNjktMzIzMjAyMDgxMzA1Njk4NA",
    "📌 Combatants Will Be Dispatched! - https://t.me/NeonFilesBot?start=Z2V0LTIxNzg0MDYwODc3MDg2OTMtMjE5MTQzODQyOTY5NjgyNg",
    "📌 Dandadan - https://t.me/NeonFilesBot?start=Z2V0LTIxMDEyMTQ1MjM2MjUxMzYtMjExNzI1NDMyOTE0ODk5Mg",
    "📌 Darling in the Franxx - https://t.me/NeonFilesBot?start=Z2V0LTUwNTI1Mzg3NDAwMTQ2NC01MzIzMjEwNDU4MjI5NzE",
    "📌 Dawn of The Witch - https://t.me/NeonFilesBot?start=Z2V0LTcwMzc0NjQ2NzM1OTE4Mi03MTY3Nzg4MDkzNDczMTU",
    "📌 Death March to the Parallel Wld - https://t.me/NeonFilesBot?start=Z2V0LTMyMDE5NDYxNzc2OTk3NTQtMzIxNTk4MTAwNzUzMzEyOA",
    "📌 Dead Mount DeathPlay - https://t.me/NeonFilesBot?start=Z2V0LTIzOTU5NDU5NTAxMjU5OTAtMjQyMjAxMDYzNDEwMjI1Ng",
    "📌 Demon King Daimao - https://t.me/NeonFilesBot?start=Z2V0LTMxMTE3MjIyNzE2MjgwNjQtMzEyNTc1NzEwMTQ2MTQzOA",
    "📌 Demon King Daimao Specials - https://t.me/NeonFilesBot?start=Z2V0LTMxMzA3Njk1NDA2ODc2NDMtMzEzOTc5MTkzMTI5NDgxMg",
    "📌 Demon Slayer S1 - https://t.me/NeonFilesBot?start=Z2V0LTEzNzY0MTU4MTE1MTU4OTMtMTQwMzQ4Mjk4MzMzNzQwMA",
    "📌 Demon Slayer Movie 01 - https://t.me/NeonFilesBot?start=Z2V0LTE0MDU0ODc5NTkwMjc4ODItMTQwNzQ5MjkzNDcxODM2NA",
    "📌 Demon Slayer S2 Part 01 - https://t.me/NeonFilesBot?start=Z2V0LTE0MDg0OTU0MjI1NjM2MDUtMTQxODUyMDMwMTAxNjAxNQ",
    "📌 Demon Slayer S2 Part 02 - https://t.me/NeonFilesBot?start=Z2V0LTE0MTk1MjI3ODg4NjEyNTYtMTQzMTU1MjY0MzAwNDE0OA",
    "📌 Demon Slayer S3 - https://t.me/NeonFilesBot?start=Z2V0LTE0MzI1NTUxMzA4NDkzODktMTQ0NDU4NDk4NDk5MjI4MQ",
    "📌 Demon Slayer S4 - https://t.me/NeonFilesBot?start=Z2V0LTE0NDU1ODc0NzI4Mzc1MjItMTQ1NDYwOTg2MzQ0NDY5MQ",
    "📌 Demon Sword Master of Excalibur - https://t.me/NeonFilesBot?start=Z2V0LTExNjg5MDA4Mjc1NTEwMDYtMTE4MTkzMzE2OTUzOTEzOQ",
    "📌 Failure Frame - https://t.me/NeonFilesBot?start=Z2V0LTIzODA5MDg2MzI0NDczNzUtMjM5Mzk0MDk3NDQzNTUwOA",
    "📌 Farming Life in another World - https://t.me/NeonFilesBot?start=Z2V0LTEwNjA2MzIxNDAyNjQ5NzgtMTA3MzY2NDQ4MjI1MzExMQ",
    "📌 Goblin Slayer S01 - https://t.me/NeonFilesBot?start=Z2V0LTE2NTkxMTczODM4NzM4NTUtMTY3MjE0OTcyNTg2MTk4OA",
    "📌 Goblin Slayer S02 - https://t.me/NeonFilesBot?start=Z2V0LTE2NzMxNTIyMTM3MDcyMjktMTY4NzE4NzA0MzU0MDYwMw",
    "📌 Goblin Slayer: G.Crown (Movie) - https://t.me/NeonFilesBot?start=Z2V0LTE2ODgxODk1MzEzODU4NDQtMTY5MDE5NDUwNzA3NjMyNg",
    "📌 Gods' Games we Play - https://t.me/NeonFilesBot?start=Z2V0LTE2OTExOTY5OTQ5MjE1NjctMTcwNTIzMTgyNDc1NDk0MQ",
    "📌 Hell's Paradise - https://t.me/NeonFilesBot?start=Z2V0LTE3MjkyOTE1MzMwNDA3MjUtMTc0MzMyNjM2Mjg3NDA5OQ",
    "📌 How a Realist Hero Rebuilt - https://t.me/NeonFilesBot?start=Z2V0LTQ3NDE3Njc1MDc5ODk5My00ODgyMTE1ODA2MzIzNjc",
    "📌 How a Realist Hero Rebuilt S2 - https://t.me/NeonFilesBot?start=Z2V0LTQ4OTIxNDA2ODQ3NzYwOC01MDMyNDg4OTgzMTA5ODI",
    "📌 How not to Summon a Demon - https://t.me/NeonFilesBot?start=Z2V0LTQxODAzNzQzMTQ2NTQ5Ny00MzEwNjk3NzM0NTM2MzA",
    "📌 Hundred - https://t.me/NeonFilesBot?start=Z2V0LTIxMzUyOTkxMTAzNjMzMzAtMjE0ODMzMTQ1MjM1MTQ2Mw",
    "📌 I Got a Cheat Skill in Another - https://t.me/NeonFilesBot?start=Z2V0LTc1OTg4NTc4NjY5MjY3OC03NzM5MjA2MTY1MjYwNTI",
    "📌 I Parry Everything - https://t.me/NeonFilesBot?start=Z2V0LTE1ODU5MzU3NzExNzEyNjItMTYwMDk3MzA4ODg0OTg3Nw",
    "📌 I Shall survive using potions - https://t.me/NeonFilesBot?start=Z2V0LTEyODMxODQ0NDE5MDg0OC0xNDEzNTA3ODYxNzg5ODE",
    "📌 I've been killing Slimes for 300 - https://t.me/NeonFilesBot?start=Z2V0LTE1NjU4ODYwMTQyNjY0NDItMTU3ODkxODM1NjI1NDU3NQ",
    "📌 I'm Quitting Heroing - https://t.me/NeonFilesBot?start=Z2V0LTEwNzU2Njk0NTc5NDM1OTMtMTA4ODcwMTc5OTkzMTcyNg",
    "📌 In another world with my S01 - https://t.me/NeonFilesBot?start=Z2V0LTE1NzM5MDU5MTcwMjgzNy0xNzA0MjI5MzM2OTA5NzA",
    "📌 In another world with my S02 - https://t.me/NeonFilesBot?start=Z2V0LTE3MTQyNTQyMTUzNjIxMS0xODQ0NTc3NjM1MjQzNDQ",
    "📌 Infinite Dendrogram - https://t.me/NeonFilesBot?start=Z2V0LTE5OTQ5NTA4MTIwMjk1OS0yMTM1Mjk5MTEwMzYzMzM",
    "📌 Isekai Cheat Magician - https://t.me/NeonFilesBot?start=Z2V0LTk3MzQxNTY5NzcyOTAxMS05ODc0NTA1Mjc1NjIzODU",
    "📌 Jujutsu Kaisen - https://t.me/NeonFilesBot?start=Z2V0LTEzMjYyOTE0MTkyNTM4NDMtMTM3NTQxMzMyMzY3MDY1Mg",
    "📌 Kaiju No 8 - https://t.me/NeonFilesBot?start=Z2V0LTEyOTgyMjE3NTk1ODcwOTUtMTMxMTI1NDEwMTU3NTIyOA",
    "📌 Knight's & Magic - https://t.me/NeonFilesBot?start=Z2V0LTI0NTgxMDAxOTY1MzA5MzItMjQ3NDE0MDAwMjA1NDc4OA",
    "📌 Konosuba! An Explosion - https://t.me/NeonFilesBot?start=Z2V0LTE1MzY4MTM4NjY3NTQ0NTMtMTU0OTg0NjIwODc0MjU4Ng",
    "📌 Konosuba Movie - https://t.me/NeonFilesBot?start=Z2V0LTE1MzE4MDE0Mjc1MjgyNDgtMTUzNDgwODg5MTA2Mzk3MQ",
    "📌 Konosuba Season 01 - https://t.me/NeonFilesBot?start=Z2V0LTE0OTQ3MDkzNzcyNTQzMzEtMTUwNTczNjc0MzU1MTk4Mg",
    "📌 Konosuba Season 02 - https://t.me/NeonFilesBot?start=Z2V0LTE1MDY3MzkyMzEzOTcyMjMtMTUxNzc2NjU5NzY5NDg3NA",
    "📌 Konosuba Season 03 - https://t.me/NeonFilesBot?start=Z2V0LTE1MTg3NjkwODU1NDAxMTUtMTUzMDc5ODkzOTY4MzAwNw",
    "📌 Log Horizon - https://t.me/NeonFilesBot?start=Z2V0LTI3MjQ3NjE5NjMzNjUwMzgtMjc1MTgyOTEzNTE4NjU0NQ",
    "📌 Log Horizon Season 02 - https://t.me/NeonFilesBot?start=Z2V0LTI3NTI4MzE2MjMwMzE3ODYtMjc3OTg5ODc5NDg1MzI5Mw",
    "📌 Log Horizon Season 03 - https://t.me/NeonFilesBot?start=Z2V0LTI3ODA5MDEyODI2OTg1MzQtMjc5NDkzNjExMjUzMTkwOA",
    "📌 Lookism - https://t.me/NeonFilesBot?start=Z2V0LTc3NDkyMzEwNDM3MTI5My03ODM5NDU0OTQ5Nzg0NjI",
    "📌 Mashle: Magic And Muscles - https://t.me/NeonFilesBot?start=Z2V0LTIzNTA4MzM5OTcwOTAxNDUtMjM2Mzg2NjMzOTA3ODI3OA",
    "📌 Mashle: Magic And Muscles S02 - https://t.me/NeonFilesBot?start=Z2V0LTIzNjU4NzEzMTQ3Njg3NjAtMjM3ODkwMzY1Njc1Njg5Mw",
    "📌 My Dress-Up Darling - https://t.me/NeonFilesBot?start=Z2V0LTI3OTU5Mzg2MDAzNzcxNDktMjgwOTk3MzQzMDIxMDUyMw",
    "📌 My Isekai life - https://t.me/NeonFilesBot?start=Z2V0LTczMTgxNjEyNzAyNTkzMC03NDQ4NDg0NjkwMTQwNjM",
    "📌 My Instant Death Ability - https://t.me/NeonFilesBot?start=Z2V0LTE1NTA4NDg2OTY1ODc4MjctMTU2NDg4MzUyNjQyMTIwMQ",
    "📌 Myriad Colors Phantom World - https://t.me/NeonFilesBot?start=Z2V0LTI5OTY0MzYxNjk0MjUzNDktMzAxMTQ3MzQ4NzEwMzk2NA",
    "📌 Myriad Colors Phantom Special - https://t.me/NeonFilesBot?start=Z2V0LTMwMTI0NzU5NzQ5NDkyMDUtMzAyMjUwMDg1MzQwMTYxNQ",
    "📌 My Unique Skill Makes Me OP - https://t.me/NeonFilesBot?start=Z2V0LTE2MTYwMTA0MDY1Mjg0OTItMTYyOTA0Mjc0ODUxNjYyNQ",
    "📌 Ningen Fushin - https://t.me/NeonFilesBot?start=Z2V0LTkwMzI0MTU0ODU2MjE0MS05MTYyNzM4OTA1NTAyNzQ",
    "📌 Noblesse - https://t.me/NeonFilesBot?start=Z2V0LTI1ODY0MTg2NDA3MjE3OC0yNzI2NzY2OTM5MDU1NTI",
    "📌 One Punch Man - https://t.me/NeonFilesBot?start=Z2V0LTQ0NjEwNzA5MTEzMjI0NS00NTkxMzk0MzMxMjAzNzg",
    "📌 One Punch Man S2 - https://t.me/NeonFilesBot?start=Z2V0LTQ2MDE0MTkyMDk2NTYxOS00NzMxNzQyNjI5NTM3NTI",
    "📌 Overflow Uncensored - https://t.me/NeonFilesBot?start=Z2V0LTE0NTU2MTIzNTEyODk5MzItMTQ2NDYzNDc0MTg5NzEwMQ",
    "📌 OverLord - https://t.me/NeonFilesBot?start=Z2V0LTg4ODIwNDIzMDg4MzUyNi05MDIyMzkwNjA3MTY5MDA",
    "📌 Our Last Crusade - https://t.me/NeonFilesBot?start=Z2V0LTc0NTg1MDk1Njg1OTMwNC03NTg4ODMyOTg4NDc0Mzc",
    "📌 Parallel World Pharmacy - https://t.me/NeonFilesBot?start=Z2V0LTY4OTcxMTYzNzUyNTgwOC03MDI3NDM5Nzk1MTM5NDE",
    "📌 Rage Of Bahamut - https://t.me/NeonFilesBot?start=Z2V0LTMxODY5MDg4NjAwMjExMzktMzIwMDk0MzY4OTg1NDUxMw",
    "📌 Re Monster - https://t.me/NeonFilesBot?start=Z2V0LTg3MjE2NDQyNTM1OTY3MC04ODUxOTY3NjczNDc4MDM",
    "📌 Record of Grancrest War - https://t.me/NeonFilesBot?start=Z2V0LTIxNTAzMzY0MjgwNDE5NDUtMjE3",
    "📌 Reborn as a Vending Machine - https://t.me/NeonFilesBot?start=Z2V0LTI1MjYyNjkzNzAwMDczMjAtMjU0MDMwNDE5OTg0MDY5NA",
    "📌 Redo of Healer - https://t.me/NeonFilesBot?start=cmdldC0xMDAyNDg3ODQ1MjQxMDAwLTEwMTU1MjAxODcyMjkxMzM",
    "📌 Reincarnated as a Sword - https://t.me/NeonFilesBot?start=Z2V0LTg0NDA5NDc2NTY5MjkyMi04NTcxMjcxMDc2ODEwNTU",
    "📌 Reincarnated as Slime S01 - https://t.me/NeonFilesBot?start=Z2V0LTU5MTQ2NzgyODY5MjE5MC02MTY1MzAwMjQ4MjMyMTU",
    "📌 Reincarnated as Slime S02 - https://t.me/NeonFilesBot?start=Z2V0LTYxNzUzMjUxMjY2ODQ1Ni02NDM1OTcxOTY2NDQ3MjI",
    "📌 Reincarnated as Slime S03 - https://t.me/NeonFilesBot?start=Z2V0LTY0NDU5OTY4NDQ4OTk2My02NzE2NjY4NTYzMTE0NzA",
    "📌 Reincarnated as Slime Movie - https://t.me/NeonFilesBot?start=Z2V0LTY3MjY2OTM0NDE1NjcxMS02NzQ2NzQzMTk4NDcxOTM",
    "📌 Reincarnatn of Strongest Exorcist - https://t.me/NeonFilesBot?start=Z2V0LTE0MjM1MzI3NDAyNDIyMi0xNTYzODgxMDM4NTc1OTY",
    "📌 Rent-A-Girlfriend - https://t.me/NeonFilesBot?start=Z2V0LTMyNjAwOTA0NzI3MjM3MzItMzI3NDEyNTMwMjU1NzEwNg",
    "📌 Rent-A-Girlfriend Season 02 - https://t.me/NeonFilesBot?start=Z2V0LTMyNzUxMjc3OTA0MDIzNDctMzI4OTE2MjYyMDIzNTcyMQ",
    "📌 Rent-A-Girlfriend Season 03 - https://t.me/NeonFilesBot?start=Z2V0LTMyOTAxNjUxMDgwODA5NjItMzMwNDE5OTkzNzkxNDMzNg",
    "📌 Restaurant to Another World S1 - https://t.me/NeonFilesBot?start=Z2V0LTI5NjUzNTkwNDYyMjI4NzgtMjk3OTM5Mzg3NjA1NjI1Mg",
    "📌 Restaurant To Another World S2 - https://t.me/NeonFilesBot?start=Z2V0LTMzMjAyMzk3NDM0MzgxOTItMzMzNDI3NDU3MzI3MTU2Ng",
    "📌 Rokka - https://t.me/NeonFilesBot?start=Z2V0LTEyNjkxNDk2MTIwNzUxMDYtMTI4MjE4MTk1NDA2MzIzOQ",
    "📌 Shangri-La Frontier - https://t.me/NeonFilesBot?start=Z2V0LTI4MTA5NzU5MTgwNTU3NjQtMjgzOTA0NTU3NzcyMjUxMg",
    "📌 Seirei Gensouki Spirit Chronicles - https://t.me/NeonFilesBot?start=Z2V0LTg1ODEyOTU5NTUyNjI5Ni04NzExNjE5Mzc1MTQ0Mjk",
    "📌 Skeleton Knight in another World - https://t.me/NeonFilesBot?start=Z2V0LTEwMzE1NTk5OTI3NTI5ODktMTA0NTU5NDgyMjU4NjM2Mw",
    "📌 Sky Wizards Academy - https://t.me/NeonFilesBot?start=Z2V0LTIwMDE5NjgyMjY5NDYyNzctMjAxNTAwMDU2ODkzNDQxMA",
    "📌 Solo Leveling - https://t.me/NeonFilesBot?start=Z2V0LTk4ODQ1MzAxNTQwNzYyNi0xMDAxNDg1MzU3Mzk1NzU5",
    "📌 Spy X Family - https://t.me/NeonFilesBot?start=Z2V0LTI2NDY1Njc5MTE0MzYyNDAtMjY3MzYzNTA4MzI1Nzc0Nw",
    "📌 Spy X Family Season 02 - https://t.me/NeonFilesBot?start=Z2V0LTI2NzU2NDAwNTg5NDgyMjktMjY4OTY3NDg4ODc4MTYwMw",
    "📌 Spy X Family : Code White - https://t.me/NeonFilesBot?start=Z2V0LTI2OTA2NzczNzY2MjY4NDQ",
    "📌 Suppose a Kid from the Last - https://t.me/NeonFilesBot?start=Z2V0LTE2MDE5NzU1NzY2OTUxMTgtMTYxNTAwNzkxODY4MzI1MQ",
    "📌 Sword Art Online S1 - https://t.me/NeonFilesBot?start=Z2V0LTE3NjAzNjg2NTYyNDMxOTYtMTc4NjQzMzM0MDIxOTQ2Mg",
    "📌 Sword Art Online S2 - https://t.me/NeonFilesBot?start=Z2V0LTE3ODc0MzU4MjgwNjQ3MDMtMTgxMjQ5ODAyNDE5NTcyOA",
    "📌 Sword Art Online S3 - https://t.me/NeonFilesBot?start=Z2V0LTE4MzI1NDc3ODExMDA1NDgtMTkwMjcyMTkzMDI2NzQxOA",
    "📌 Sword Art Online S4 - https://t.me/NeonFilesBot?start=Z2V0LTE5MDM3MjQ0MTgxMTI2NTktMTkyNzc4NDEyNjM5ODQ0Mw",
    "📌 Sword Art Online: Gun Gale - https://t.me/NeonFilesBot?start=Z2V0LTE4MTM1MDA1MTIwNDA5NjktMTgzMTU0NTI5MzI1NTMwNw",
    "📌 Sword Art Online Movies - https://t.me/NeonFilesBot?start=Z2V0LTE5NTE4NDM4MzQ2ODQyMjctMTk1NTg1Mzc4NjA2NTE5MQ",
    "📌 Sweet Reincarnation - https://t.me/NeonFilesBot?start=Z2V0LTkxNzI3NjM3ODM5NTUxNS05MzAzMDg3MjAzODM2NDg",
    "📌 The Daily Life of the Immortal S1 - https://t.me/NeonFilesBot?start=Z2V0LTExODI5MzU2NTczODQzODAtMTE5ODk3NTQ2MjkwODIzNg",
    "📌 The Daily Life of the Immortal S2 - https://t.me/NeonFilesBot?start=Z2V0LTExOTk5Nzc5NTA3NTM0NzctMTIxMzAxMDI5Mjc0MTYxMA",
    "📌 The Daily Life of the Immortal S3 - https://t.me/NeonFilesBot?start=Z2V0LTEyMTQwMTI3ODA1ODY4NTEtMTIyNzA0NTEyMjU3NDk4NA",
    "📌 The Daily Life of the Immortal S4 - https://t.me/NeonFilesBot?start=Z2V0LTEyMjgwNDc2MTA0MjAyMjUtMTI0MTA3OTk1MjQwODM1OA",
    "📌 The Dreaming Boy is a Realist - https://t.me/NeonFilesBot?start=Z2V0LTIyMzc1NTI4NzA1Nzc5MTItMjI1MDU4NTIxMjU2NjA0NQ",
    "📌 The Eminence in Shadow S1 - https://t.me/NeonFilesBot?start=Z2V0LTExMTg3NzY0MzUyODg5NTYtMTEzOTgyODY4MDAzOTAxNw",
    "📌 The Eminence in Shadow S2 - https://t.me/NeonFilesBot?start=Z2V0LTExNDA4MzExNjc4ODQyNTgtMTE1Mzg2MzUwOTg3MjM5MQ",
    "📌 The Executioner and Her Way of - https://t.me/NeonFilesBot?start=Z2V0LTI0OTMxODcyNzExMTQzNjctMjUwNzIyMjEwMDk0Nzc0MQ",
    "📌 The Foolish Angel Dances with - https://t.me/NeonFilesBot?start=Z2V0LTMwMjM1MDMzNDEyNDY4NTYtMzAzNzUzODE3MTA4MDIzMA",
    "📌 The God of HighSchool - https://t.me/NeonFilesBot?start=Z2V0LTI5ODAzOTYzNjM5MDE0OTMtMjk5NTQzMzY4MTU4MDEwOA",
    "📌 The Greatest Alchemist - https://t.me/NeonFilesBot?start=Z2V0LTM3MDUxOTUwNzYwMTA3MzYtMzcxOTIyOTkwNTg0NDExMA",
    "📌 The Greatest Demon lord Reborn - https://t.me/NeonFilesBot?start=Z2V0LTEwNDY1OTczMTA0MzE2MDQtMTA1OTYyOTY1MjQxOTczNw",
    "📌 The Hidden dungeon only - https://t.me/NeonFilesBot?start=Z2V0LTE0Nzk2NzIwNTk1NzU3MTYtMTQ5MzcwNjg4OTQwOTA5MA",
    "📌 The IceBlade Sorcerer - https://t.me/NeonFilesBot?start=Z2V0LTcxNzc4MTI5NzE5MjU1Ni03MzA4MTM2MzkxODA2ODk",
    "📌 The Misfit of Demon King - https://t.me/NeonFilesBot?start=Z2V0LTIyNTI1OTAxODgyNTY1MjctMjI2NjYyNTAxODA4OTkwMQ",
    "📌 The Misfit of Demon King S02 - https://t.me/NeonFilesBot?start=Z2V0LTIyNjg2Mjk5OTM3ODAzODMtMjI5MzY5MjE4OTkxMTQwOA",
    "📌 The Ossan Newbie Adventurer - https://t.me/NeonFilesBot?start=Z2V0LTMxNzA4NjkwNTQ0OTcyODMtMzE4NTkwNjM3MjE3NTg5OA",
    "📌 The Rising of the Shield Hero S1 - https://t.me/NeonFilesBot?start=Z2V0LTUzNTMyODUwOTM1ODY5NC01NjEzOTMxOTMzMzQ5NjA",
    "📌 The Rising of the Shield Hero S2 - https://t.me/NeonFilesBot?start=Z2V0LTU2MjM5NTY4MTE4MDIwMS01NzY0MzA1MTEwMTM1NzU",
    "📌 The Rising of the Shield Hero S3 - https://t.me/NeonFilesBot?start=Z2V0LTU3NzQzMjk5ODg1ODgxNi01OTA0NjUzNDA4NDY5NDk",
    "📌 The Slime Diaries - https://t.me/NeonFilesBot?start=Z2V0LTY3NTY3NjgwNzY5MjQzNC02ODg3MDkxNDk2ODA1Njc",
    "📌 The Strongest Sage with weakst - https://t.me/NeonFilesBot?start=Z2V0LTEwMTY1MjI2NzUwNzQzNzQtMTAyOTU1NTAxNzA2MjUwNw",
    "📌 The Testament of Sister - https://t.me/NeonFilesBot?start=Z2V0LTI2MDE0NTU5NTg0MDAzOTUtMjYxNjQ5MzI3NjA3OTAxMA",
    "📌 The Testament of Sister S02 - https://t.me/NeonFilesBot?start=Z2V0LTI2MTc0OTU3NjM5MjQyNTEtMjYzMDUyODEwNTkxMjM4NA",
    "📌 The Testament of Sister Special - https://t.me/NeonFilesBot?start=Z2V0LTI2MzE1MzA1OTM3NTc2MjUtMjY0NTU2NTQyMzU5MDk5OQ",
    "📌 The Weakest Tamer Began - https://t.me/NeonFilesBot?start=Z2V0LTI1ODY0MTg2NDA3MjE3ODAtMjYwMDQ1MzQ3MDU1NTE1NA",
    "📌 Tomo-Chan is a Girl ! - https://t.me/NeonFilesBot?start=Z2V0LTM0MDI0NDM3NDY3NDc5NTQtMzQxNzQ4MTA2NDQyNjU2OQ",
    "📌 Toradora ! - https://t.me/NeonFilesBot?start=Z2V0LTMzNjUzNTE2OTY0NzQwMzctMzM5MzQyMTM1NjE0MDc4NQ",
    "📌 Toradora ! Specials - https://t.me/NeonFilesBot?start=Z2V0LTMzOTQ0MjM4NDM5ODYwMjYtMzQwMDQzODc3MTA1NzQ3Mg",
    "📌 Tower Of God - https://t.me/NeonFilesBot?start=Z2V0LTMwOTU2ODI0NjYxMDQyMDgtMzExMDcxOTc4Mzc4MjgyMw",
    "📌 Tower Of God Season 02 - https://t.me/NeonFilesBot?start=Z2V0LTMwNjY2MTAzMTg1OTIyMTktMzA5NDY3OTk3ODI1ODk2Nw",
    "📌 Transformers Prime S1 - https://t.me/NeonFilesBot?start=Z2V0LTM0Mzg1MzMzMDkxNzY2My0zNzA5MjA1MDI3MzkxNzA",
    "📌 Transformers Prime S2 - https://t.me/NeonFilesBot?start=Z2V0LTM3MTkyMjk5MDU4NDQxMS0zOTg5OTAxNjI0MDU5MTg",
    "📌 Transformers Prime S3 - https://t.me/NeonFilesBot?start=Z2V0LTM5OTk5MjY1MDI1MTE1OS00MTQwMjc0ODAwODQ1MzM",
    "📌 Transformers Prime Movie - https://t.me/NeonFilesBot?start=Z2V0LTQxNTAyOTk2NzkyOTc3NC00MTcwMzQ5NDM2MjAyNTY",
    "📌 TsukiMichi Moonlit Fantasy S1 - https://t.me/NeonFilesBot?start=Z2V0LTkzMTMxMTIwODIyODg4OS05NDQzNDM1NTAyMTcwMjI",
    "📌 TsukiMichi Moonlit Fantasy S2 - https://t.me/NeonFilesBot?start=Z2V0LTk0NTM0NjAzODA2MjI2My05NzE0MTA3MjIwMzg1Mjk",
    "📌 UQ Holder! - https://t.me/NeonFilesBot?start=Z2V0LTE5NjQ4NzYxNzY2NzIzNjAtMTk4NTkyODQyMTQyMjQyMQ",
    "📌 Unwanted undead Adventurer - https://t.me/NeonFilesBot?start=Z2V0LTI3MzY3OTE4MTc1MDc5My0yODY3MTE1MjM3Mzg5MjY",
    "📌 Vermeil in Gold - https://t.me/NeonFilesBot?start=Z2V0LTMxNDA3OTQ0MTkxNDAwNTMtMzE1NDgyOTI0ODk3MzQyNw",
    "📌 Violet Evergarden - https://t.me/NeonFilesBot?start=Z2V0LTIzMTI3Mzk0NTg5NzA5ODctMjM0NDgxOTA3MDAxODY5OQ",
    "📌 Wind Breaker - https://t.me/NeonFilesBot?start=Z2V0LTEwODk3MDQyODc3NzY5NjctMTEwMzczOTExNzYxMDM0MQ",
    "📌 Wistoria : wand and sword - https://t.me/NeonFilesBot?start=Z2V0LTMxNTc4MzY3MTI1MDkxNS0zMjg4MTYwMTMyMzkwNDg",
    "📌 Wrong way to use Healing Magic - https://t.me/NeonFilesBot?start=Z2V0LTEyODMxODQ0NDE5MDg0ODAtMTI5NzIxOTI3MTc0MTg1NA"
    ]
    

# MyselfNeon
# Don't Remove Credit 🥺
# Telegram Channel @NeonFiles
